version: '3.8'
services:
  app:
    build: ../app
    ports:
     - "8080:8080"
    networks:
      - proxynet
  reverse-proxy:
    build: ../nginx-sample
    ports:
      - "80:80"
    networks:
      - proxynet
networks:
  proxynet:
    driver: bridge